export const SET_TRANSACTIONS_TOTAL_PLN = "SET_TRANSACTIONS_TOTAL_PLN";

export const SET_EUR_VALUE_REQUEST = "SET_EUR_VALUE_REQUEST";

export const SET_EUR_VALUE = "SET_EUR_VALUE";

export const BEGIN_DELETION_TRANSITION = "BEGIN_DELETION_TRANSITION";

export const DELETE_TRANSACTION_REQUEST = "DELETE_TRANSACTION_REQUEST";

export const DELETE_TRANSACTION = "DELETE_TRANSACTION";

export const SET_TRANSACTIONS_TOTAL_EUR = "SET_TRANSACTIONS_TOTAL_EUR";

export const SET_TRANSACTION_FOCUSED_REQUEST = "SET_TRANSACTION_FOCUSED_REQUEST";

export const TOGGLE_DELETE_OPTION = "TOGGLE_DELETE_OPTION";

export const SET_TRANSACTION_AMOUNT_REQUEST = "SET_TRANSACTION_AMOUNT_REQUEST";

export const SET_TRANSACTION_AMOUNT = "SET_TRANSACTION_AMOUNT";

export const SET_TRANSACTION_NAME_REQUEST = "SET_TRANSACTION_NAME_REQUEST";

export const SET_TRANSACTION_NAME = "SET_TRANSACTION_NAME";

export const ADD_TRANSACTION_REQUEST = "ADD_TRANSACTION_REQUEST";

export const ADD_TRANSACTION = "ADD_TRANSACTION";

export const SHOW_TRANSACTION = "SHOW_TRANSACTION";

export const SET_TRANSACTION_CONTENT_HEIGHT_REQUEST = "SET_TRANSACTION_CONTENT_HEIGHT_REQUEST";

export const SET_TRANSACTION_CONTENT_HEIGHT = "SET_TRANSACTION_CONTENT_HEIGHT";